DROP TABLE IF EXISTS taxunit_lg_18day11_state1;
CREATE TABLE taxunit_lg_18day11_state1
(
DAY TINYINT,
PERIOD TINYINT,
NPLANTSR1 TINYINT,
NPLANTSS1 TINYINT,
NSOLDR1 FLOAT,
NSOLDS1 FLOAT,
TOTALCOSTR1 FLOAT,
TOTALCOSTS1 FLOAT,
SURPLUS FLOAT,
PRICE FLOAT,
PRIMARY KEY(NPLANTSR1, NPLANTSS1, DAY, PERIOD)
);
LOAD DATA LOCAL INFILE "C:\Users\Samuel\Dropbox\Capital Investment\Optimization\taxunit_lg_18day11_state1_sql_output1.csv" INTO TABLE taxunit_lg_18day11_state1 COLUMNS TERMINATED BY ',';


DROP TABLE IF EXISTS taxunit_lg_18day11_state2;
CREATE TABLE taxunit_lg_18day11_state2
(
DAY TINYINT,
PERIOD TINYINT,
NPLANTSR1 TINYINT,
NPLANTSS1 TINYINT,
NSOLDR1 FLOAT,
NSOLDS1 FLOAT,
TOTALCOSTR1 FLOAT,
TOTALCOSTS1 FLOAT,
SURPLUS FLOAT,
PRICE FLOAT,
PRIMARY KEY(NPLANTSR1, NPLANTSS1, DAY, PERIOD)
);
LOAD DATA LOCAL INFILE "C:\Users\Samuel\Dropbox\Capital Investment\Optimization\taxunit_lg_18day11_state2_sql_output1.csv" INTO TABLE taxunit_lg_18day11_state2 COLUMNS TERMINATED BY ',';
